/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.openapi.generator.aicc.api;

import com.openapi.generator.aicc.dto.ComResponseAction;
import com.openapi.generator.aicc.dto.ComResponseActionAuthority;
import com.openapi.generator.aicc.dto.ComResponseActionAuthorityList;
import com.openapi.generator.aicc.dto.ComResponseActionList;
import com.openapi.generator.aicc.dto.ComResponseCommonCode;
import com.openapi.generator.aicc.dto.ComResponseCommonCodeGroup;
import com.openapi.generator.aicc.dto.ComResponseCommonCodeGroupList;
import com.openapi.generator.aicc.dto.ComResponseCommonCodeList;
import com.openapi.generator.aicc.dto.ComResponseListMenuTree;
import com.openapi.generator.aicc.dto.ComResponseMenu;
import com.openapi.generator.aicc.dto.ComResponseMenuAuthority;
import com.openapi.generator.aicc.dto.ComResponseMenuAuthorityList;
import com.openapi.generator.aicc.dto.ComResponseMenuList;
import com.openapi.generator.aicc.dto.ComResponseRole;
import com.openapi.generator.aicc.dto.ComResponseRoleList;
import com.openapi.generator.aicc.dto.DeleteActionRequest;
import com.openapi.generator.aicc.dto.DeleteCommonCodeGroupRequest;
import com.openapi.generator.aicc.dto.DeleteCommonCodeRequest;
import com.openapi.generator.aicc.dto.DeleteMenuRequest;
import com.openapi.generator.aicc.dto.DeleteRoleRequest;
import com.openapi.generator.aicc.dto.RetrieveActionAuthorityListRequest;
import com.openapi.generator.aicc.dto.RetrieveActionAuthorityRequest;
import com.openapi.generator.aicc.dto.RetrieveActionListRequest;
import com.openapi.generator.aicc.dto.RetrieveActionRequest;
import com.openapi.generator.aicc.dto.RetrieveCommonCodeGroupListRequest;
import com.openapi.generator.aicc.dto.RetrieveCommonCodeGroupRequest;
import com.openapi.generator.aicc.dto.RetrieveCommonCodeListRequest;
import com.openapi.generator.aicc.dto.RetrieveCommonCodeRequest;
import com.openapi.generator.aicc.dto.RetrieveMenuAuthorityListRequest;
import com.openapi.generator.aicc.dto.RetrieveMenuAuthorityRequest;
import com.openapi.generator.aicc.dto.RetrieveMenuListRequest;
import com.openapi.generator.aicc.dto.RetrieveMenuRequest;
import com.openapi.generator.aicc.dto.RetrieveRoleListRequest;
import com.openapi.generator.aicc.dto.RetrieveRoleRequest;
import com.openapi.generator.aicc.dto.UpdateActionAuthorityRequest;
import com.openapi.generator.aicc.dto.UpdateActionRequest;
import com.openapi.generator.aicc.dto.UpdateCommonCodeGroupRequest;
import com.openapi.generator.aicc.dto.UpdateCommonCodeRequest;
import com.openapi.generator.aicc.dto.UpdateMenuAuthorityRequest;
import com.openapi.generator.aicc.dto.UpdateMenuRequest;
import com.openapi.generator.aicc.dto.UpdateRoleRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-19T16:30:08.398412+09:00[Asia/Seoul]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "메뉴/액션관리", description = "the 메뉴/액션관리 API")
public interface AdminApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CREATE_ACTION = "/admin/menuAction/action/createAction";
    /**
     * POST /admin/menuAction/action/createAction : 액션 등록
     * 액션 등록
     *
     * @param updateActionRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "createAction",
        summary = "액션 등록",
        description = "액션 등록",
        tags = { "메뉴/액션관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_CREATE_ACTION,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> createAction(
        @Parameter(name = "UpdateActionRequest", description = "", required = true) @Valid @RequestBody UpdateActionRequest updateActionRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREATE_COMMON_CODE = "/admin/code/createCommonCode";
    /**
     * POST /admin/code/createCommonCode : 공통코드 등록
     * 공통코드 등록
     *
     * @param updateCommonCodeRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "createCommonCode",
        summary = "공통코드 등록",
        description = "공통코드 등록",
        tags = { "공통코드 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_CREATE_COMMON_CODE,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> createCommonCode(
        @Parameter(name = "UpdateCommonCodeRequest", description = "", required = true) @Valid @RequestBody UpdateCommonCodeRequest updateCommonCodeRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREATE_COMMON_CODE_GROUP = "/admin/code/createCommonCodeGroup";
    /**
     * POST /admin/code/createCommonCodeGroup : 그룹코드 등록
     * 그룹코드 등록
     *
     * @param updateCommonCodeGroupRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "createCommonCodeGroup",
        summary = "그룹코드 등록",
        description = "그룹코드 등록",
        tags = { "공통코드 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_CREATE_COMMON_CODE_GROUP,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> createCommonCodeGroup(
        @Parameter(name = "UpdateCommonCodeGroupRequest", description = "", required = true) @Valid @RequestBody UpdateCommonCodeGroupRequest updateCommonCodeGroupRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREATE_MENU = "/admin/menuAction/menu/createMenu";
    /**
     * POST /admin/menuAction/menu/createMenu : 메뉴 등록
     * 메뉴 등록
     *
     * @param updateMenuRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "createMenu",
        summary = "메뉴 등록",
        description = "메뉴 등록",
        tags = { "메뉴/액션관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_CREATE_MENU,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> createMenu(
        @Parameter(name = "UpdateMenuRequest", description = "", required = true) @Valid @RequestBody UpdateMenuRequest updateMenuRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREATE_ROLE = "/admin/role/createRole";
    /**
     * POST /admin/role/createRole : 권한 등록
     * 권한 등록
     *
     * @param updateRoleRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "createRole",
        summary = "권한 등록",
        description = "권한 등록",
        tags = { "권한관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_CREATE_ROLE,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> createRole(
        @Parameter(name = "UpdateRoleRequest", description = "", required = true) @Valid @RequestBody UpdateRoleRequest updateRoleRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DELETE_ACTION = "/admin/menuAction/action/deleteAction";
    /**
     * POST /admin/menuAction/action/deleteAction : 액션 삭제
     * 액션 삭제
     *
     * @param deleteActionRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "deleteAction",
        summary = "액션 삭제",
        description = "액션 삭제",
        tags = { "메뉴/액션관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_DELETE_ACTION,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> deleteAction(
        @Parameter(name = "DeleteActionRequest", description = "", required = true) @Valid @RequestBody DeleteActionRequest deleteActionRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DELETE_COMMON_CODE = "/admin/code/deleteCommonCode";
    /**
     * POST /admin/code/deleteCommonCode : 공통코드 삭제
     * 공통코드 삭제
     *
     * @param deleteCommonCodeRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "deleteCommonCode",
        summary = "공통코드 삭제",
        description = "공통코드 삭제",
        tags = { "공통코드 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_DELETE_COMMON_CODE,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> deleteCommonCode(
        @Parameter(name = "DeleteCommonCodeRequest", description = "", required = true) @Valid @RequestBody DeleteCommonCodeRequest deleteCommonCodeRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DELETE_COMMON_CODE_GROUP = "/admin/code/deleteCommonCodeGroup";
    /**
     * POST /admin/code/deleteCommonCodeGroup : 그룹코드 삭제
     * 그룹코드 삭제
     *
     * @param deleteCommonCodeGroupRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "deleteCommonCodeGroup",
        summary = "그룹코드 삭제",
        description = "그룹코드 삭제",
        tags = { "공통코드 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_DELETE_COMMON_CODE_GROUP,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> deleteCommonCodeGroup(
        @Parameter(name = "DeleteCommonCodeGroupRequest", description = "", required = true) @Valid @RequestBody DeleteCommonCodeGroupRequest deleteCommonCodeGroupRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DELETE_MENU = "/admin/menuAction/menu/deleteMenu";
    /**
     * POST /admin/menuAction/menu/deleteMenu : 메뉴 삭제
     * 메뉴 삭제
     *
     * @param deleteMenuRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "deleteMenu",
        summary = "메뉴 삭제",
        description = "메뉴 삭제",
        tags = { "메뉴/액션관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_DELETE_MENU,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> deleteMenu(
        @Parameter(name = "DeleteMenuRequest", description = "", required = true) @Valid @RequestBody DeleteMenuRequest deleteMenuRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DELETE_ROLE = "/admin/role/deleteRole";
    /**
     * POST /admin/role/deleteRole : 권한 삭제
     * 권한 삭제
     *
     * @param deleteRoleRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "deleteRole",
        summary = "권한 삭제",
        description = "권한 삭제",
        tags = { "권한관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_DELETE_ROLE,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> deleteRole(
        @Parameter(name = "DeleteRoleRequest", description = "", required = true) @Valid @RequestBody DeleteRoleRequest deleteRoleRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_ACTION = "/admin/menuAction/action/retrieveAction";
    /**
     * POST /admin/menuAction/action/retrieveAction : 액션 상세 조회
     * 액션 상세 조회
     *
     * @param retrieveActionRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveAction",
        summary = "액션 상세 조회",
        description = "액션 상세 조회",
        tags = { "메뉴/액션관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseAction.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_RETRIEVE_ACTION,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseAction> retrieveAction(
        @Parameter(name = "RetrieveActionRequest", description = "", required = true) @Valid @RequestBody RetrieveActionRequest retrieveActionRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"rolNm\" : \"rolNm\", \"actionUrl\" : \"actionUrl\", \"actionId\" : \"actionId\", \"menuId\" : \"menuId\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"updDt\" : \"updDt\", \"actionNm\" : \"actionNm\", \"creDt\" : \"creDt\" }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_ACTION_AUTHORITY = "/admin/authority/action/retrieveActionAuthority";
    /**
     * POST /admin/authority/action/retrieveActionAuthority : 액션 권한 상세 조회
     * 액션 권한 상세 조회
     *
     * @param retrieveActionAuthorityRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveActionAuthority",
        summary = "액션 권한 상세 조회",
        description = "액션 권한 상세 조회",
        tags = { "메뉴 액션 권한 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseActionAuthority.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_RETRIEVE_ACTION_AUTHORITY,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseActionAuthority> retrieveActionAuthority(
        @Parameter(name = "RetrieveActionAuthorityRequest", description = "", required = true) @Valid @RequestBody RetrieveActionAuthorityRequest retrieveActionAuthorityRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"authYn\" : \"authYn\", \"rolNm\" : \"rolNm\", \"actionUrl\" : \"actionUrl\", \"actionId\" : \"actionId\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"updDt\" : \"updDt\", \"creDt\" : \"creDt\" }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_ACTION_AUTHORITY_LIST = "/admin/authority/action/retrieveActionAuthorityList";
    /**
     * POST /admin/authority/action/retrieveActionAuthorityList : 액션 권한 목록 조회
     * 액션 권한 목록 조회
     *
     * @param retrieveActionAuthorityListRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveActionAuthorityList",
        summary = "액션 권한 목록 조회",
        description = "액션 권한 목록 조회",
        tags = { "메뉴 액션 권한 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseActionAuthorityList.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_RETRIEVE_ACTION_AUTHORITY_LIST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseActionAuthorityList> retrieveActionAuthorityList(
        @Parameter(name = "RetrieveActionAuthorityListRequest", description = "", required = true) @Valid @RequestBody RetrieveActionAuthorityListRequest retrieveActionAuthorityListRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"list\" : [ { \"authYn\" : \"authYn\", \"rolNm\" : \"rolNm\", \"actionUrl\" : \"actionUrl\", \"actionId\" : \"actionId\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"updDt\" : \"updDt\", \"creDt\" : \"creDt\" }, { \"authYn\" : \"authYn\", \"rolNm\" : \"rolNm\", \"actionUrl\" : \"actionUrl\", \"actionId\" : \"actionId\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"updDt\" : \"updDt\", \"creDt\" : \"creDt\" } ], \"totalCount\" : 6 }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_ACTION_LIST = "/admin/menuAction/action/retrieveActionList";
    /**
     * POST /admin/menuAction/action/retrieveActionList : 액션 목록 조회
     * 액션 목록 조회
     *
     * @param retrieveActionListRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveActionList",
        summary = "액션 목록 조회",
        description = "액션 목록 조회",
        tags = { "메뉴/액션관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseActionList.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_RETRIEVE_ACTION_LIST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseActionList> retrieveActionList(
        @Parameter(name = "RetrieveActionListRequest", description = "", required = true) @Valid @RequestBody RetrieveActionListRequest retrieveActionListRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"list\" : [ { \"rolNm\" : \"rolNm\", \"actionUrl\" : \"actionUrl\", \"actionId\" : \"actionId\", \"menuId\" : \"menuId\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"updDt\" : \"updDt\", \"actionNm\" : \"actionNm\", \"creDt\" : \"creDt\" }, { \"rolNm\" : \"rolNm\", \"actionUrl\" : \"actionUrl\", \"actionId\" : \"actionId\", \"menuId\" : \"menuId\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"updDt\" : \"updDt\", \"actionNm\" : \"actionNm\", \"creDt\" : \"creDt\" } ], \"totalCount\" : 6 }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_AUTHORITY_TREE = "/admin/authority/retrieveAuthorityTree";
    /**
     * POST /admin/authority/retrieveAuthorityTree : 메뉴/액션 트리 조회
     * 메뉴/액션 트리 조회
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveAuthorityTree",
        summary = "메뉴/액션 트리 조회",
        description = "메뉴/액션 트리 조회",
        tags = { "메뉴 액션 권한 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseListMenuTree.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_RETRIEVE_AUTHORITY_TREE,
        produces = { "application/json" }
    )
    default ResponseEntity<ComResponseListMenuTree> retrieveAuthorityTree(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : [ { \"id\" : \"id\", \"label\" : \"label\", \"type\" : \"type\", \"parentId\" : \"parentId\" }, { \"id\" : \"id\", \"label\" : \"label\", \"type\" : \"type\", \"parentId\" : \"parentId\" } ], \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_COMMON_CODE = "/admin/code/retrieveCommonCode";
    /**
     * POST /admin/code/retrieveCommonCode : 공통코드 상세 조회
     * 공통코드 상세 조회
     *
     * @param retrieveCommonCodeRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveCommonCode",
        summary = "공통코드 상세 조회",
        description = "공통코드 상세 조회",
        tags = { "공통코드 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseCommonCode.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_RETRIEVE_COMMON_CODE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseCommonCode> retrieveCommonCode(
        @Parameter(name = "RetrieveCommonCodeRequest", description = "", required = true) @Valid @RequestBody RetrieveCommonCodeRequest retrieveCommonCodeRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"cmmCd\" : \"cmmCd\", \"rolNm\" : \"rolNm\", \"cmmNm\" : \"cmmNm\", \"grpCd\" : \"grpCd\", \"useYn\" : \"useYn\", \"comment\" : \"comment\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"updDt\" : \"updDt\", \"creDt\" : \"creDt\" }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_COMMON_CODE_GROUP = "/admin/code/retrieveCommonCodeGroup";
    /**
     * POST /admin/code/retrieveCommonCodeGroup : 그룹 코드 상세 조회
     * 그룹 코드 상세 조회
     *
     * @param retrieveCommonCodeGroupRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveCommonCodeGroup",
        summary = "그룹 코드 상세 조회",
        description = "그룹 코드 상세 조회",
        tags = { "공통코드 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseCommonCodeGroup.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_RETRIEVE_COMMON_CODE_GROUP,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseCommonCodeGroup> retrieveCommonCodeGroup(
        @Parameter(name = "RetrieveCommonCodeGroupRequest", description = "", required = true) @Valid @RequestBody RetrieveCommonCodeGroupRequest retrieveCommonCodeGroupRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"grpCdNm\" : \"grpCdNm\", \"rolNm\" : \"rolNm\", \"grpCd\" : \"grpCd\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"updDt\" : \"updDt\", \"creDt\" : \"creDt\" }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_COMMON_CODE_GROUP_LIST = "/admin/code/retrieveCommonCodeGroupList";
    /**
     * POST /admin/code/retrieveCommonCodeGroupList : 그룹코드 목록 조회
     * 그룹코드 목록 조회
     *
     * @param retrieveCommonCodeGroupListRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveCommonCodeGroupList",
        summary = "그룹코드 목록 조회",
        description = "그룹코드 목록 조회",
        tags = { "공통코드 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseCommonCodeGroupList.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_RETRIEVE_COMMON_CODE_GROUP_LIST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseCommonCodeGroupList> retrieveCommonCodeGroupList(
        @Parameter(name = "RetrieveCommonCodeGroupListRequest", description = "", required = true) @Valid @RequestBody RetrieveCommonCodeGroupListRequest retrieveCommonCodeGroupListRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"list\" : [ { \"grpCdNm\" : \"grpCdNm\", \"rolNm\" : \"rolNm\", \"grpCd\" : \"grpCd\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"updDt\" : \"updDt\", \"creDt\" : \"creDt\" }, { \"grpCdNm\" : \"grpCdNm\", \"rolNm\" : \"rolNm\", \"grpCd\" : \"grpCd\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"updDt\" : \"updDt\", \"creDt\" : \"creDt\" } ], \"totalCount\" : 6 }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_COMMON_CODE_LIST = "/admin/code/retrieveCommonCodeList";
    /**
     * POST /admin/code/retrieveCommonCodeList : 공통코드 목록 조회
     * 공통코드 목록 조회
     *
     * @param retrieveCommonCodeListRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveCommonCodeList",
        summary = "공통코드 목록 조회",
        description = "공통코드 목록 조회",
        tags = { "공통코드 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseCommonCodeList.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_RETRIEVE_COMMON_CODE_LIST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseCommonCodeList> retrieveCommonCodeList(
        @Parameter(name = "RetrieveCommonCodeListRequest", description = "", required = true) @Valid @RequestBody RetrieveCommonCodeListRequest retrieveCommonCodeListRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"list\" : [ { \"cmmCd\" : \"cmmCd\", \"rolNm\" : \"rolNm\", \"cmmNm\" : \"cmmNm\", \"grpCd\" : \"grpCd\", \"useYn\" : \"useYn\", \"comment\" : \"comment\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"updDt\" : \"updDt\", \"creDt\" : \"creDt\" }, { \"cmmCd\" : \"cmmCd\", \"rolNm\" : \"rolNm\", \"cmmNm\" : \"cmmNm\", \"grpCd\" : \"grpCd\", \"useYn\" : \"useYn\", \"comment\" : \"comment\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"updDt\" : \"updDt\", \"creDt\" : \"creDt\" } ], \"totalCount\" : 6 }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_MENU = "/admin/menuAction/menu/retrieveMenu";
    /**
     * POST /admin/menuAction/menu/retrieveMenu : 메뉴 상세 조회
     * 메뉴 상세 조회
     *
     * @param retrieveMenuRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveMenu",
        summary = "메뉴 상세 조회",
        description = "메뉴 상세 조회",
        tags = { "메뉴/액션관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseMenu.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_RETRIEVE_MENU,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseMenu> retrieveMenu(
        @Parameter(name = "RetrieveMenuRequest", description = "", required = true) @Valid @RequestBody RetrieveMenuRequest retrieveMenuRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"rolNm\" : \"rolNm\", \"menuUrl\" : \"menuUrl\", \"menuOrd\" : 6, \"menuId\" : \"menuId\", \"mdlCd\" : \"mdlCd\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"headerMenuYn\" : \"headerMenuYn\", \"updDt\" : \"updDt\", \"menuNm\" : \"menuNm\", \"creDt\" : \"creDt\" }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_MENU_AUTHORITY = "/admin/authority/menu/retrieveMenuAuthority";
    /**
     * POST /admin/authority/menu/retrieveMenuAuthority : 메뉴 권한 상세 조회
     * 메뉴 권한 상세 조회
     *
     * @param retrieveMenuAuthorityRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveMenuAuthority",
        summary = "메뉴 권한 상세 조회",
        description = "메뉴 권한 상세 조회",
        tags = { "메뉴 액션 권한 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseMenuAuthority.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_RETRIEVE_MENU_AUTHORITY,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseMenuAuthority> retrieveMenuAuthority(
        @Parameter(name = "RetrieveMenuAuthorityRequest", description = "", required = true) @Valid @RequestBody RetrieveMenuAuthorityRequest retrieveMenuAuthorityRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"menuOrd\" : \"menuOrd\", \"updUsr\" : \"updUsr\", \"creDt\" : \"creDt\", \"authYn\" : \"authYn\", \"rolNm\" : \"rolNm\", \"menuUrl\" : \"menuUrl\", \"menuId\" : \"menuId\", \"mdlCd\" : \"mdlCd\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"mdlNm\" : \"mdlNm\", \"updDt\" : \"updDt\", \"menuNm\" : \"menuNm\" }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_MENU_AUTHORITY_LIST = "/admin/authority/menu/retrieveMenuAuthorityList";
    /**
     * POST /admin/authority/menu/retrieveMenuAuthorityList : 메뉴 권한 목록 조회
     * 메뉴 권한 목록 조회
     *
     * @param retrieveMenuAuthorityListRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveMenuAuthorityList",
        summary = "메뉴 권한 목록 조회",
        description = "메뉴 권한 목록 조회",
        tags = { "메뉴 액션 권한 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseMenuAuthorityList.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_RETRIEVE_MENU_AUTHORITY_LIST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseMenuAuthorityList> retrieveMenuAuthorityList(
        @Parameter(name = "RetrieveMenuAuthorityListRequest", description = "", required = true) @Valid @RequestBody RetrieveMenuAuthorityListRequest retrieveMenuAuthorityListRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"endDate\" : \"2025-05-08\", \"limit\" : 10, \"currentPage\" : 1, \"list\" : [ { \"menuOrd\" : \"menuOrd\", \"updUsr\" : \"updUsr\", \"creDt\" : \"creDt\", \"authYn\" : \"authYn\", \"rolNm\" : \"rolNm\", \"menuUrl\" : \"menuUrl\", \"menuId\" : \"menuId\", \"mdlCd\" : \"mdlCd\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"mdlNm\" : \"mdlNm\", \"updDt\" : \"updDt\", \"menuNm\" : \"menuNm\" }, { \"menuOrd\" : \"menuOrd\", \"updUsr\" : \"updUsr\", \"creDt\" : \"creDt\", \"authYn\" : \"authYn\", \"rolNm\" : \"rolNm\", \"menuUrl\" : \"menuUrl\", \"menuId\" : \"menuId\", \"mdlCd\" : \"mdlCd\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"mdlNm\" : \"mdlNm\", \"updDt\" : \"updDt\", \"menuNm\" : \"menuNm\" } ], \"totalCount\" : 6, \"startDate\" : \"2025-05-05\" }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_MENU_LIST = "/admin/menuAction/menu/retrieveMenuList";
    /**
     * POST /admin/menuAction/menu/retrieveMenuList : 메뉴 목록 조회
     * 메뉴 목록 조회
     *
     * @param retrieveMenuListRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveMenuList",
        summary = "메뉴 목록 조회",
        description = "메뉴 목록 조회",
        tags = { "메뉴/액션관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseMenuList.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_RETRIEVE_MENU_LIST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseMenuList> retrieveMenuList(
        @Parameter(name = "RetrieveMenuListRequest", description = "", required = true) @Valid @RequestBody RetrieveMenuListRequest retrieveMenuListRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"list\" : [ { \"rolNm\" : \"rolNm\", \"menuUrl\" : \"menuUrl\", \"menuOrd\" : 6, \"menuId\" : \"menuId\", \"mdlCd\" : \"mdlCd\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"headerMenuYn\" : \"headerMenuYn\", \"updDt\" : \"updDt\", \"menuNm\" : \"menuNm\", \"creDt\" : \"creDt\" }, { \"rolNm\" : \"rolNm\", \"menuUrl\" : \"menuUrl\", \"menuOrd\" : 6, \"menuId\" : \"menuId\", \"mdlCd\" : \"mdlCd\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"headerMenuYn\" : \"headerMenuYn\", \"updDt\" : \"updDt\", \"menuNm\" : \"menuNm\", \"creDt\" : \"creDt\" } ], \"totalCount\" : 6 }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_ROLE = "/admin/role/retrieveRole";
    /**
     * POST /admin/role/retrieveRole : 권한 상세 조회
     * 권한 상세 조회
     *
     * @param retrieveRoleRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveRole",
        summary = "권한 상세 조회",
        description = "권한 상세 조회",
        tags = { "권한관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseRole.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_RETRIEVE_ROLE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseRole> retrieveRole(
        @Parameter(name = "RetrieveRoleRequest", description = "", required = true) @Valid @RequestBody RetrieveRoleRequest retrieveRoleRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"rolDesc\" : \"rolDesc\", \"rolNm\" : \"rolNm\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"updDt\" : \"updDt\", \"creDt\" : \"creDt\" }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_ROLE_LIST = "/admin/role/retrieveRoleList";
    /**
     * POST /admin/role/retrieveRoleList : 권한 목록 조회
     * 권한 목록 조회
     *
     * @param retrieveRoleListRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveRoleList",
        summary = "권한 목록 조회",
        description = "권한 목록 조회",
        tags = { "권한관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseRoleList.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_RETRIEVE_ROLE_LIST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseRoleList> retrieveRoleList(
        @Parameter(name = "RetrieveRoleListRequest", description = "", required = true) @Valid @RequestBody RetrieveRoleListRequest retrieveRoleListRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"list\" : [ { \"rolDesc\" : \"rolDesc\", \"rolNm\" : \"rolNm\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"updDt\" : \"updDt\", \"creDt\" : \"creDt\" }, { \"rolDesc\" : \"rolDesc\", \"rolNm\" : \"rolNm\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updUsr\" : \"updUsr\", \"updDt\" : \"updDt\", \"creDt\" : \"creDt\" } ], \"totalCount\" : 6 }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_ACTION = "/admin/menuAction/action/updateAction";
    /**
     * POST /admin/menuAction/action/updateAction : 액션 수정
     * 액션 수정
     *
     * @param updateActionRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "updateAction",
        summary = "액션 수정",
        description = "액션 수정",
        tags = { "메뉴/액션관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_UPDATE_ACTION,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> updateAction(
        @Parameter(name = "UpdateActionRequest", description = "", required = true) @Valid @RequestBody UpdateActionRequest updateActionRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_ACTION_AUTHORITY = "/admin/authority/action/updateActionAuthority";
    /**
     * POST /admin/authority/action/updateActionAuthority : 액션 권한 수정
     * 액션 권한 수정
     *
     * @param updateActionAuthorityRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "updateActionAuthority",
        summary = "액션 권한 수정",
        description = "액션 권한 수정",
        tags = { "메뉴 액션 권한 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_UPDATE_ACTION_AUTHORITY,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> updateActionAuthority(
        @Parameter(name = "UpdateActionAuthorityRequest", description = "", required = true) @Valid @RequestBody UpdateActionAuthorityRequest updateActionAuthorityRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_COMMON_CODE = "/admin/code/updateCommonCode";
    /**
     * POST /admin/code/updateCommonCode : 공통코드 수정
     * 공통코드 수정
     *
     * @param updateCommonCodeRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "updateCommonCode",
        summary = "공통코드 수정",
        description = "공통코드 수정",
        tags = { "공통코드 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_UPDATE_COMMON_CODE,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> updateCommonCode(
        @Parameter(name = "UpdateCommonCodeRequest", description = "", required = true) @Valid @RequestBody UpdateCommonCodeRequest updateCommonCodeRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_COMMON_CODE_GROUP = "/admin/code/updateCommonCodeGroup";
    /**
     * POST /admin/code/updateCommonCodeGroup : 그룹코드 수정
     * 그룹코드 수정
     *
     * @param updateCommonCodeGroupRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "updateCommonCodeGroup",
        summary = "그룹코드 수정",
        description = "그룹코드 수정",
        tags = { "공통코드 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_UPDATE_COMMON_CODE_GROUP,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> updateCommonCodeGroup(
        @Parameter(name = "UpdateCommonCodeGroupRequest", description = "", required = true) @Valid @RequestBody UpdateCommonCodeGroupRequest updateCommonCodeGroupRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_MENU = "/admin/menuAction/menu/updateMenu";
    /**
     * POST /admin/menuAction/menu/updateMenu : 메뉴 수정
     * 메뉴 수정
     *
     * @param updateMenuRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "updateMenu",
        summary = "메뉴 수정",
        description = "메뉴 수정",
        tags = { "메뉴/액션관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_UPDATE_MENU,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> updateMenu(
        @Parameter(name = "UpdateMenuRequest", description = "", required = true) @Valid @RequestBody UpdateMenuRequest updateMenuRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_MENU_AUTHORITY = "/admin/authority/menu/updateMenuAuthority";
    /**
     * POST /admin/authority/menu/updateMenuAuthority : 메뉴 권한 수정
     * 메뉴 권한 수정
     *
     * @param updateMenuAuthorityRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "updateMenuAuthority",
        summary = "메뉴 권한 수정",
        description = "메뉴 권한 수정",
        tags = { "메뉴 액션 권한 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_UPDATE_MENU_AUTHORITY,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> updateMenuAuthority(
        @Parameter(name = "UpdateMenuAuthorityRequest", description = "", required = true) @Valid @RequestBody UpdateMenuAuthorityRequest updateMenuAuthorityRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_ROLE = "/admin/role/updateRole";
    /**
     * POST /admin/role/updateRole : 권한 수정
     * 권한 수정
     *
     * @param updateRoleRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "updateRole",
        summary = "권한 수정",
        description = "권한 수정",
        tags = { "권한관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AdminApi.PATH_UPDATE_ROLE,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> updateRole(
        @Parameter(name = "UpdateRoleRequest", description = "", required = true) @Valid @RequestBody UpdateRoleRequest updateRoleRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
