/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.openapi.generator.aicc.api;

import com.openapi.generator.aicc.dto.ComResponseDevice;
import com.openapi.generator.aicc.dto.ComResponseDeviceList;
import com.openapi.generator.aicc.dto.ComResponseInteger;
import com.openapi.generator.aicc.dto.CreateDeviceRequest;
import com.openapi.generator.aicc.dto.DownloadDeviceListRequest;
import com.openapi.generator.aicc.dto.RetrieveDeviceListRequest;
import com.openapi.generator.aicc.dto.RetrieveDeviceRequest;
import com.openapi.generator.aicc.dto.UpdateDeviceRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-19T16:30:08.398412+09:00[Asia/Seoul]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "서비스 등록 - 디바이스 모델 등록", description = "서비스 등록 - 디바이스 모델 등록")
public interface DeviceApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CREATE_DEVICE = "/device/createDevice";
    /**
     * POST /device/createDevice : 디바이스 모델 등록
     * 디바이스 모델 등록
     *
     * @param createDeviceRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "createDevice",
        summary = "디바이스 모델 등록",
        description = "디바이스 모델 등록",
        tags = { "서비스 등록 - 디바이스 모델 등록" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = DeviceApi.PATH_CREATE_DEVICE,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> createDevice(
        @Parameter(name = "CreateDeviceRequest", description = "", required = true) @Valid @RequestBody CreateDeviceRequest createDeviceRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DELETE_DEVICE = "/device/deleteDevice";
    /**
     * POST /device/deleteDevice : 디바이스 모델 삭제
     * 디바이스 모델 삭제
     *
     * @param retrieveDeviceRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "deleteDevice",
        summary = "디바이스 모델 삭제",
        description = "디바이스 모델 삭제",
        tags = { "서비스 등록 - 디바이스 모델 등록" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseInteger.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = DeviceApi.PATH_DELETE_DEVICE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseInteger> deleteDevice(
        @Parameter(name = "RetrieveDeviceRequest", description = "", required = true) @Valid @RequestBody RetrieveDeviceRequest retrieveDeviceRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : 6, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DOWNLOAD_DEVICE_LIST = "/device/downloadDeviceList";
    /**
     * POST /device/downloadDeviceList : 디바이스 모델 엑셀 다운로드
     * 디바이스 모델 엑셀 다운로드
     *
     * @param downloadDeviceListRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "downloadDeviceList",
        summary = "디바이스 모델 엑셀 다운로드",
        description = "디바이스 모델 엑셀 다운로드",
        tags = { "서비스 등록 - 디바이스 모델 등록" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = DeviceApi.PATH_DOWNLOAD_DEVICE_LIST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> downloadDeviceList(
        @Parameter(name = "DownloadDeviceListRequest", description = "", required = true) @Valid @RequestBody DownloadDeviceListRequest downloadDeviceListRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_DEVICE = "/device/retrieveDevice";
    /**
     * POST /device/retrieveDevice : 디바이스 모델 상세 조회
     * 디바이스 모델 상세 조회
     *
     * @param retrieveDeviceRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveDevice",
        summary = "디바이스 모델 상세 조회",
        description = "디바이스 모델 상세 조회",
        tags = { "서비스 등록 - 디바이스 모델 등록" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseDevice.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = DeviceApi.PATH_RETRIEVE_DEVICE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseDevice> retrieveDevice(
        @Parameter(name = "RetrieveDeviceRequest", description = "", required = true) @Valid @RequestBody RetrieveDeviceRequest retrieveDeviceRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"deviceType\" : \"deviceType\", \"cmpCd\" : \"cmpCd\", \"cmpNm\" : \"cmpNm\", \"anTypeList\" : [ 10, 10000000 ], \"modemNm\" : \"modemNm\", \"deviceNm\" : \"deviceNm\", \"modemCd\" : \"modemCd\", \"updUsr\" : \"updUsr\", \"deviceCd\" : \"deviceCd\", \"creDt\" : \"creDt\", \"deviceEmail\" : \"manager@abacus.com\", \"rolNm\" : \"rolNm\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"anType\" : \"10000010\", \"updDt\" : \"updDt\", \"deviceManu\" : \"manager\" }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_DEVICE_LIST = "/device/retrieveDeviceList";
    /**
     * POST /device/retrieveDeviceList : 디바이스 모델 목록 조회
     * 디바이스 모델 목록 조회
     *
     * @param retrieveDeviceListRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveDeviceList",
        summary = "디바이스 모델 목록 조회",
        description = "디바이스 모델 목록 조회",
        tags = { "서비스 등록 - 디바이스 모델 등록" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseDeviceList.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = DeviceApi.PATH_RETRIEVE_DEVICE_LIST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseDeviceList> retrieveDeviceList(
        @Parameter(name = "RetrieveDeviceListRequest", description = "", required = true) @Valid @RequestBody RetrieveDeviceListRequest retrieveDeviceListRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"list\" : [ { \"deviceType\" : \"deviceType\", \"cmpCd\" : \"cmpCd\", \"cmpNm\" : \"cmpNm\", \"anTypeList\" : [ 10, 10000000 ], \"modemNm\" : \"modemNm\", \"deviceNm\" : \"deviceNm\", \"modemCd\" : \"modemCd\", \"updUsr\" : \"updUsr\", \"deviceCd\" : \"deviceCd\", \"creDt\" : \"creDt\", \"deviceEmail\" : \"manager@abacus.com\", \"rolNm\" : \"rolNm\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"anType\" : \"10000010\", \"updDt\" : \"updDt\", \"deviceManu\" : \"manager\" }, { \"deviceType\" : \"deviceType\", \"cmpCd\" : \"cmpCd\", \"cmpNm\" : \"cmpNm\", \"anTypeList\" : [ 10, 10000000 ], \"modemNm\" : \"modemNm\", \"deviceNm\" : \"deviceNm\", \"modemCd\" : \"modemCd\", \"updUsr\" : \"updUsr\", \"deviceCd\" : \"deviceCd\", \"creDt\" : \"creDt\", \"deviceEmail\" : \"manager@abacus.com\", \"rolNm\" : \"rolNm\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"anType\" : \"10000010\", \"updDt\" : \"updDt\", \"deviceManu\" : \"manager\" } ], \"totalCount\" : 6 }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_DEVICE = "/device/updateDevice";
    /**
     * POST /device/updateDevice : 디바이스 모델 수정
     * 디바이스 모델 수정
     *
     * @param updateDeviceRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "updateDevice",
        summary = "디바이스 모델 수정",
        description = "디바이스 모델 수정",
        tags = { "서비스 등록 - 디바이스 모델 등록" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = DeviceApi.PATH_UPDATE_DEVICE,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> updateDevice(
        @Parameter(name = "UpdateDeviceRequest", description = "", required = true) @Valid @RequestBody UpdateDeviceRequest updateDeviceRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
