/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.openapi.generator.aicc.api;

import com.openapi.generator.aicc.dto.ComResponseSessionInfo;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-19T16:30:08.398412+09:00[Asia/Seoul]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "공통api", description = "the 공통api API")
public interface GetSessionApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_GET_SESSION = "/getSession";
    /**
     * POST /getSession : 세션 조회
     * 세션 조회
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getSession",
        summary = "세션 조회",
        description = "세션 조회",
        tags = { "공통api" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseSessionInfo.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = GetSessionApi.PATH_GET_SESSION,
        produces = { "application/json" }
    )
    default ResponseEntity<ComResponseSessionInfo> getSession(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"menuList\" : [ { \"menuUrl\" : \"menuUrl\", \"menuOrd\" : \"menuOrd\", \"menuId\" : \"menuId\", \"headerMenuYn\" : \"headerMenuYn\", \"menuNm\" : \"menuNm\" }, { \"menuUrl\" : \"menuUrl\", \"menuOrd\" : \"menuOrd\", \"menuId\" : \"menuId\", \"headerMenuYn\" : \"headerMenuYn\", \"menuNm\" : \"menuNm\" } ], \"user\" : { \"userNm\" : \"userNm\", \"cmpCd\" : \"cmpCd\", \"roles\" : [ \"roles\", \"roles\" ], \"credentialsNonExpired\" : true, \"userId\" : \"userId\", \"authorities\" : [ { \"authority\" : \"authority\" }, { \"authority\" : \"authority\" } ], \"enabled\" : true, \"password\" : \"password\", \"secondCmpCd\" : \"secondCmpCd\", \"serviceList\" : [ \"serviceList\", \"serviceList\" ], \"accountNonExpired\" : true, \"cmpType\" : \"cmpType\", \"email\" : \"email\", \"username\" : \"username\", \"accountNonLocked\" : true } }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
