/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.openapi.generator.aicc.api;

import com.openapi.generator.aicc.dto.ComResponseLogSearch;
import com.openapi.generator.aicc.dto.DownloadLogHistoryFileRequest;
import com.openapi.generator.aicc.dto.RetrieveLogHistoryRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-19T16:30:08.398412+09:00[Asia/Seoul]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "로그 조회 - 이력 로그 조회", description = "이력 로그 조회")
public interface LogsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_DOWNLOAD_LOG_HISTORY_FILE = "/logs/logHistory/downloadLogHistoryFile";
    /**
     * POST /logs/logHistory/downloadLogHistoryFile : 로그 조회 - 이력 로그 파일 다운로드
     * 이력 로그 파일 다운로드
     *
     * @param downloadLogHistoryFileRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "downloadLogHistoryFile",
        summary = "로그 조회 - 이력 로그 파일 다운로드",
        description = "이력 로그 파일 다운로드",
        tags = { "로그 조회 - 이력 로그 조회" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = LogsApi.PATH_DOWNLOAD_LOG_HISTORY_FILE,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> downloadLogHistoryFile(
        @Parameter(name = "DownloadLogHistoryFileRequest", description = "", required = true) @Valid @RequestBody DownloadLogHistoryFileRequest downloadLogHistoryFileRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_LOG_HISTORY = "/logs/logHistory/retrieveLogHistory";
    /**
     * POST /logs/logHistory/retrieveLogHistory : 로그 조회 - 이력 로그 목록 조회
     * 이력 로그 목록 조회
     *
     * @param retrieveLogHistoryRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveLogHistory",
        summary = "로그 조회 - 이력 로그 목록 조회",
        description = "이력 로그 목록 조회",
        tags = { "로그 조회 - 이력 로그 조회" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseLogSearch.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = LogsApi.PATH_RETRIEVE_LOG_HISTORY,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseLogSearch> retrieveLogHistory(
        @Parameter(name = "RetrieveLogHistoryRequest", description = "", required = true) @Valid @RequestBody RetrieveLogHistoryRequest retrieveLogHistoryRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"totalPage\" : 1, \"filePath\" : \"filePath\", \"currentPage\" : 6, \"logs\" : \"logs\" }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
