/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.openapi.generator.aicc.api;

import com.openapi.generator.aicc.dto.ComResponseCtnList;
import com.openapi.generator.aicc.dto.ComResponseFirmware;
import com.openapi.generator.aicc.dto.ComResponseFirmwareList;
import com.openapi.generator.aicc.dto.ComResponseFirmwareVersionList;
import com.openapi.generator.aicc.dto.DeleteFirmwareRequest;
import com.openapi.generator.aicc.dto.DownloadFirmwareListRequest;
import com.openapi.generator.aicc.dto.DownloadFirmwareRequest;
import org.springframework.lang.Nullable;
import com.openapi.generator.aicc.dto.RetrieveCtnListRequest;
import com.openapi.generator.aicc.dto.RetrieveFirmwareVersionListRequest;
import com.openapi.generator.aicc.dto.RetrieveFwApplyTargetListRequest;
import com.openapi.generator.aicc.dto.RetrieveModuleFirmwareListRequest;
import com.openapi.generator.aicc.dto.RetrieveModuleFirmwareRequest;
import com.openapi.generator.aicc.dto.UpdateFirmwareRequestRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-19T16:30:08.398412+09:00[Asia/Seoul]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "디바이스 관리 - 모듈 펌웨어 관리", description = "디바이스 관리 - 모듈 펌웨어 관리 api")
public interface ModuleFirmwareApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CREATE_MODULE_FIRMWARE = "/moduleFirmware/createFirmware";
    /**
     * POST /moduleFirmware/createFirmware : 펌웨어 등록
     * 펌웨어 등록
     *
     * @param svcCd 서비스 코드 (optional)
     * @param deviceCd 디바이스 모델 코드 (optional)
     * @param fwVer 펌웨어 버전 (optional)
     * @param fwApplyTarget 펌웨어 적용 대상 (optional)
     * @param fwDesc 펌웨어 설명 (optional)
     * @param betaVerYn 베타버전여부 (optional)
     * @param fwFile 업로드 파일 (optional)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "createModuleFirmware",
        summary = "펌웨어 등록",
        description = "펌웨어 등록",
        tags = { "디바이스 관리 - 모듈 펌웨어 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ModuleFirmwareApi.PATH_CREATE_MODULE_FIRMWARE,
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<Void> createModuleFirmware(
        @Parameter(name = "svcCd", description = "서비스 코드") @Valid @RequestParam(value = "svcCd", required = false) String svcCd,
        @Parameter(name = "deviceCd", description = "디바이스 모델 코드") @Valid @RequestParam(value = "deviceCd", required = false) String deviceCd,
        @Parameter(name = "fwVer", description = "펌웨어 버전") @Valid @RequestParam(value = "fwVer", required = false) String fwVer,
        @Parameter(name = "fwApplyTarget", description = "펌웨어 적용 대상") @Valid @RequestParam(value = "fwApplyTarget", required = false) String fwApplyTarget,
        @Parameter(name = "fwDesc", description = "펌웨어 설명") @Valid @RequestParam(value = "fwDesc", required = false) String fwDesc,
        @Parameter(name = "betaVerYn", description = "베타버전여부") @Valid @RequestParam(value = "betaVerYn", required = false) String betaVerYn,
        @Parameter(name = "fwFile", description = "업로드 파일") @RequestPart(value = "fwFile", required = false) MultipartFile fwFile
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DELETE_FIRMWARE = "/moduleFirmware/deleteFirmware";
    /**
     * POST /moduleFirmware/deleteFirmware : 모듈 펌웨어 삭제
     * 모듈 펌웨어 삭제
     *
     * @param deleteFirmwareRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "deleteFirmware",
        summary = "모듈 펌웨어 삭제",
        description = "모듈 펌웨어 삭제",
        tags = { "디바이스 관리 - 모듈 펌웨어 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ModuleFirmwareApi.PATH_DELETE_FIRMWARE,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> deleteFirmware(
        @Parameter(name = "DeleteFirmwareRequest", description = "", required = true) @Valid @RequestBody DeleteFirmwareRequest deleteFirmwareRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DOWNLOAD_FIRMWARE = "/moduleFirmware/downloadFirmware";
    /**
     * POST /moduleFirmware/downloadFirmware : 모듈 펌웨어 다운로드
     * 모듈 펌웨어 다운로드
     *
     * @param downloadFirmwareRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "downloadFirmware",
        summary = "모듈 펌웨어 다운로드",
        description = "모듈 펌웨어 다운로드",
        tags = { "디바이스 관리 - 모듈 펌웨어 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ModuleFirmwareApi.PATH_DOWNLOAD_FIRMWARE,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> downloadFirmware(
        @Parameter(name = "DownloadFirmwareRequest", description = "", required = true) @Valid @RequestBody DownloadFirmwareRequest downloadFirmwareRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DOWNLOAD_FIRMWARE_LIST = "/moduleFirmware/downloadFirmwareList";
    /**
     * POST /moduleFirmware/downloadFirmwareList : 모듈 펌웨어 목록 엑셀 다운로드
     * 펌웨어 목록 엑셀 다운로드
     *
     * @param downloadFirmwareListRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "downloadFirmwareList",
        summary = "모듈 펌웨어 목록 엑셀 다운로드",
        description = "펌웨어 목록 엑셀 다운로드",
        tags = { "디바이스 관리 - 모듈 펌웨어 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ModuleFirmwareApi.PATH_DOWNLOAD_FIRMWARE_LIST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> downloadFirmwareList(
        @Parameter(name = "DownloadFirmwareListRequest", description = "", required = true) @Valid @RequestBody DownloadFirmwareListRequest downloadFirmwareListRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_CTN_LIST = "/moduleFirmware/retrieveCtnList";
    /**
     * POST /moduleFirmware/retrieveCtnList : 모듈 펌웨어 CTN 목록 조회
     * 모듈 펌웨어 CTN 목록 조회
     *
     * @param retrieveCtnListRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveCtnList",
        summary = "모듈 펌웨어 CTN 목록 조회",
        description = "모듈 펌웨어 CTN 목록 조회",
        tags = { "디바이스 관리 - 모듈 펌웨어 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseCtnList.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ModuleFirmwareApi.PATH_RETRIEVE_CTN_LIST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseCtnList> retrieveCtnList(
        @Parameter(name = "RetrieveCtnListRequest", description = "", required = true) @Valid @RequestBody RetrieveCtnListRequest retrieveCtnListRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"list\" : [ { \"fwVer\" : \"fwVer\", \"swInst\" : \"swInst\", \"registered\" : \"registered\", \"entityId\" : \"entityId\", \"svcCd\" : \"svcCd\", \"deviceCd\" : \"deviceCd\", \"updUsr\" : \"updUsr\", \"creDt\" : \"creDt\", \"mac\" : \"mac\", \"fwStatus\" : \"fwStatus\", \"swVer\" : \"swVer\", \"swActStatus\" : \"swActStatus\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"swUninst\" : \"swUninst\", \"ctn\" : \"ctn\", \"updDt\" : \"updDt\", \"swInstStatus\" : \"swInstStatus\" }, { \"fwVer\" : \"fwVer\", \"swInst\" : \"swInst\", \"registered\" : \"registered\", \"entityId\" : \"entityId\", \"svcCd\" : \"svcCd\", \"deviceCd\" : \"deviceCd\", \"updUsr\" : \"updUsr\", \"creDt\" : \"creDt\", \"mac\" : \"mac\", \"fwStatus\" : \"fwStatus\", \"swVer\" : \"swVer\", \"swActStatus\" : \"swActStatus\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"swUninst\" : \"swUninst\", \"ctn\" : \"ctn\", \"updDt\" : \"updDt\", \"swInstStatus\" : \"swInstStatus\" } ], \"totalCount\" : 6 }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_FIRMWARE_VERSION_LIST = "/moduleFirmware/retrieveFirmwareVersionList";
    /**
     * POST /moduleFirmware/retrieveFirmwareVersionList : 펌웨어 버전 목록 조회
     * 펌웨어 버전 목록 조회
     *
     * @param retrieveFirmwareVersionListRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveFirmwareVersionList",
        summary = "펌웨어 버전 목록 조회",
        description = "펌웨어 버전 목록 조회",
        tags = { "디바이스 관리 - 모듈 펌웨어 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseFirmwareVersionList.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ModuleFirmwareApi.PATH_RETRIEVE_FIRMWARE_VERSION_LIST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseFirmwareVersionList> retrieveFirmwareVersionList(
        @Parameter(name = "RetrieveFirmwareVersionListRequest", description = "", required = true) @Valid @RequestBody RetrieveFirmwareVersionListRequest retrieveFirmwareVersionListRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"list\" : [ { \"fwNm\" : \"fwNm\", \"betaVerYn\" : \"betaVerYn\", \"fwVer\" : \"fwVer\", \"deviceCd\" : \"deviceCd\", \"failCnt\" : 1, \"rolNm\" : \"rolNm\", \"useYn\" : \"useYn\", \"fwFilePath\" : \"fwFilePath\", \"fwCd\" : \"fwCd\", \"successCnt\" : 6, \"reqYn\" : \"reqYn\", \"deviceNm\" : \"deviceNm\", \"svcCd\" : \"svcCd\", \"updUsr\" : \"updUsr\", \"creDt\" : \"creDt\", \"fwApplyTarget\" : \"fwApplyTarget\", \"fwSize\" : \"fwSize\", \"inprogressCnt\" : 5, \"svcNm\" : \"svcNm\", \"ctnList\" : \"ctnList\", \"fwDesc\" : \"fwDesc\", \"creUsr\" : \"creUsr\", \"updDt\" : \"updDt\", \"fwChecksum\" : \"fwChecksum\", \"lastFwVer\" : \"lastFwVer\" }, { \"fwNm\" : \"fwNm\", \"betaVerYn\" : \"betaVerYn\", \"fwVer\" : \"fwVer\", \"deviceCd\" : \"deviceCd\", \"failCnt\" : 1, \"rolNm\" : \"rolNm\", \"useYn\" : \"useYn\", \"fwFilePath\" : \"fwFilePath\", \"fwCd\" : \"fwCd\", \"successCnt\" : 6, \"reqYn\" : \"reqYn\", \"deviceNm\" : \"deviceNm\", \"svcCd\" : \"svcCd\", \"updUsr\" : \"updUsr\", \"creDt\" : \"creDt\", \"fwApplyTarget\" : \"fwApplyTarget\", \"fwSize\" : \"fwSize\", \"inprogressCnt\" : 5, \"svcNm\" : \"svcNm\", \"ctnList\" : \"ctnList\", \"fwDesc\" : \"fwDesc\", \"creUsr\" : \"creUsr\", \"updDt\" : \"updDt\", \"fwChecksum\" : \"fwChecksum\", \"lastFwVer\" : \"lastFwVer\" } ], \"totalCount\" : 5 }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_FW_APPLY_TARGET_LIST = "/moduleFirmware/retrieveFwApplyTargetList";
    /**
     * POST /moduleFirmware/retrieveFwApplyTargetList : 모듈 펌웨어 적용 대상 목록 조회
     * 모듈 펌웨어 적용 대상 목록 조회
     *
     * @param retrieveFwApplyTargetListRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveFwApplyTargetList",
        summary = "모듈 펌웨어 적용 대상 목록 조회",
        description = "모듈 펌웨어 적용 대상 목록 조회",
        tags = { "디바이스 관리 - 모듈 펌웨어 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseFirmwareList.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ModuleFirmwareApi.PATH_RETRIEVE_FW_APPLY_TARGET_LIST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseFirmwareList> retrieveFwApplyTargetList(
        @Parameter(name = "RetrieveFwApplyTargetListRequest", description = "", required = true) @Valid @RequestBody RetrieveFwApplyTargetListRequest retrieveFwApplyTargetListRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"list\" : [ { \"fwNm\" : \"merged.xml\", \"fwFilePath\" : \"/mawp/firmware/0078/56/1.0.0\", \"fwCd\" : \"9600\", \"betaVerYn\" : \"betaVerYn\", \"reqYn\" : \"reqYn\", \"fwVer\" : \"1.0.0\", \"deviceNm\" : \"CG-GW100\", \"svcCd\" : \"0078\", \"updUsr\" : \"updUsr\", \"deviceCd\" : \"561\", \"creDt\" : \"creDt\", \"fwApplyTarget\" : \"fwApplyTarget\", \"fwSize\" : \"3297862\", \"ctnCount\" : 6, \"rolNm\" : \"rolNm\", \"svcNm\" : \"0078\", \"ctnList\" : \"ctnList\", \"fwDesc\" : \"fwDesc\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updDt\" : \"updDt\", \"fwChecksum\" : \"fwChecksum\", \"lastFwVer\" : \"2.0.0\" }, { \"fwNm\" : \"merged.xml\", \"fwFilePath\" : \"/mawp/firmware/0078/56/1.0.0\", \"fwCd\" : \"9600\", \"betaVerYn\" : \"betaVerYn\", \"reqYn\" : \"reqYn\", \"fwVer\" : \"1.0.0\", \"deviceNm\" : \"CG-GW100\", \"svcCd\" : \"0078\", \"updUsr\" : \"updUsr\", \"deviceCd\" : \"561\", \"creDt\" : \"creDt\", \"fwApplyTarget\" : \"fwApplyTarget\", \"fwSize\" : \"3297862\", \"ctnCount\" : 6, \"rolNm\" : \"rolNm\", \"svcNm\" : \"0078\", \"ctnList\" : \"ctnList\", \"fwDesc\" : \"fwDesc\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updDt\" : \"updDt\", \"fwChecksum\" : \"fwChecksum\", \"lastFwVer\" : \"2.0.0\" } ], \"totalCount\" : 1 }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_MODULE_FIRMWARE = "/moduleFirmware/retrieveFirmware";
    /**
     * POST /moduleFirmware/retrieveFirmware : 모듈 펌웨어 상세 조회
     * 모듈 펌웨어 상세 조회
     *
     * @param retrieveModuleFirmwareRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveModuleFirmware",
        summary = "모듈 펌웨어 상세 조회",
        description = "모듈 펌웨어 상세 조회",
        tags = { "디바이스 관리 - 모듈 펌웨어 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseFirmware.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ModuleFirmwareApi.PATH_RETRIEVE_MODULE_FIRMWARE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseFirmware> retrieveModuleFirmware(
        @Parameter(name = "RetrieveModuleFirmwareRequest", description = "", required = true) @Valid @RequestBody RetrieveModuleFirmwareRequest retrieveModuleFirmwareRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"fwNm\" : \"merged.xml\", \"fwFilePath\" : \"/mawp/firmware/0078/56/1.0.0\", \"fwCd\" : \"9600\", \"betaVerYn\" : \"betaVerYn\", \"reqYn\" : \"reqYn\", \"fwVer\" : \"1.0.0\", \"deviceNm\" : \"CG-GW100\", \"svcCd\" : \"0078\", \"updUsr\" : \"updUsr\", \"deviceCd\" : \"561\", \"creDt\" : \"creDt\", \"fwApplyTarget\" : \"fwApplyTarget\", \"fwSize\" : \"3297862\", \"ctnCount\" : 6, \"rolNm\" : \"rolNm\", \"svcNm\" : \"0078\", \"ctnList\" : \"ctnList\", \"fwDesc\" : \"fwDesc\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updDt\" : \"updDt\", \"fwChecksum\" : \"fwChecksum\", \"lastFwVer\" : \"2.0.0\" }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_MODULE_FIRMWARE_LIST = "/moduleFirmware/retrieveFirmwareList";
    /**
     * POST /moduleFirmware/retrieveFirmwareList : 모듈 펌웨어 목록조회
     * 모듈 펌웨어 목록조회
     *
     * @param retrieveModuleFirmwareListRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveModuleFirmwareList",
        summary = "모듈 펌웨어 목록조회",
        description = "모듈 펌웨어 목록조회",
        tags = { "디바이스 관리 - 모듈 펌웨어 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseFirmwareList.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ModuleFirmwareApi.PATH_RETRIEVE_MODULE_FIRMWARE_LIST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseFirmwareList> retrieveModuleFirmwareList(
        @Parameter(name = "RetrieveModuleFirmwareListRequest", description = "", required = true) @Valid @RequestBody RetrieveModuleFirmwareListRequest retrieveModuleFirmwareListRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"list\" : [ { \"fwNm\" : \"merged.xml\", \"fwFilePath\" : \"/mawp/firmware/0078/56/1.0.0\", \"fwCd\" : \"9600\", \"betaVerYn\" : \"betaVerYn\", \"reqYn\" : \"reqYn\", \"fwVer\" : \"1.0.0\", \"deviceNm\" : \"CG-GW100\", \"svcCd\" : \"0078\", \"updUsr\" : \"updUsr\", \"deviceCd\" : \"561\", \"creDt\" : \"creDt\", \"fwApplyTarget\" : \"fwApplyTarget\", \"fwSize\" : \"3297862\", \"ctnCount\" : 6, \"rolNm\" : \"rolNm\", \"svcNm\" : \"0078\", \"ctnList\" : \"ctnList\", \"fwDesc\" : \"fwDesc\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updDt\" : \"updDt\", \"fwChecksum\" : \"fwChecksum\", \"lastFwVer\" : \"2.0.0\" }, { \"fwNm\" : \"merged.xml\", \"fwFilePath\" : \"/mawp/firmware/0078/56/1.0.0\", \"fwCd\" : \"9600\", \"betaVerYn\" : \"betaVerYn\", \"reqYn\" : \"reqYn\", \"fwVer\" : \"1.0.0\", \"deviceNm\" : \"CG-GW100\", \"svcCd\" : \"0078\", \"updUsr\" : \"updUsr\", \"deviceCd\" : \"561\", \"creDt\" : \"creDt\", \"fwApplyTarget\" : \"fwApplyTarget\", \"fwSize\" : \"3297862\", \"ctnCount\" : 6, \"rolNm\" : \"rolNm\", \"svcNm\" : \"0078\", \"ctnList\" : \"ctnList\", \"fwDesc\" : \"fwDesc\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updDt\" : \"updDt\", \"fwChecksum\" : \"fwChecksum\", \"lastFwVer\" : \"2.0.0\" } ], \"totalCount\" : 1 }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_FIRMWARE = "/moduleFirmware/updateFirmware";
    /**
     * POST /moduleFirmware/updateFirmware : 모듈 펌웨어 수정
     * 모듈 펌웨어 수정
     *
     * @param fwCd 펌웨어 코드 (optional)
     * @param svcCd 서비스 코드 (optional)
     * @param deviceCd 디바이스 모델 코드 (optional)
     * @param fwVer 펌웨어 버전 (optional)
     * @param fwApplyTarget 펌웨어 적용 대상 (optional)
     * @param fwDesc 펌웨어 설명 (optional)
     * @param betaVerYn 베타버전여부 (optional)
     * @param fwFile 업로드 파일 (optional)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "updateFirmware",
        summary = "모듈 펌웨어 수정",
        description = "모듈 펌웨어 수정",
        tags = { "디바이스 관리 - 모듈 펌웨어 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ModuleFirmwareApi.PATH_UPDATE_FIRMWARE,
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<Void> updateFirmware(
        @Parameter(name = "fwCd", description = "펌웨어 코드") @Valid @RequestParam(value = "fwCd", required = false) String fwCd,
        @Parameter(name = "svcCd", description = "서비스 코드") @Valid @RequestParam(value = "svcCd", required = false) String svcCd,
        @Parameter(name = "deviceCd", description = "디바이스 모델 코드") @Valid @RequestParam(value = "deviceCd", required = false) String deviceCd,
        @Parameter(name = "fwVer", description = "펌웨어 버전") @Valid @RequestParam(value = "fwVer", required = false) String fwVer,
        @Parameter(name = "fwApplyTarget", description = "펌웨어 적용 대상") @Valid @RequestParam(value = "fwApplyTarget", required = false) String fwApplyTarget,
        @Parameter(name = "fwDesc", description = "펌웨어 설명") @Valid @RequestParam(value = "fwDesc", required = false) String fwDesc,
        @Parameter(name = "betaVerYn", description = "베타버전여부") @Valid @RequestParam(value = "betaVerYn", required = false) String betaVerYn,
        @Parameter(name = "fwFile", description = "업로드 파일") @RequestPart(value = "fwFile", required = false) MultipartFile fwFile
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_FIRMWARE_REQUEST = "/moduleFirmware/updateFirmwareRequest";
    /**
     * POST /moduleFirmware/updateFirmwareRequest : 모듈 펌웨어 업데이트 요청
     * 모듈 펌웨어 업데이트 요청
     *
     * @param updateFirmwareRequestRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "updateFirmwareRequest",
        summary = "모듈 펌웨어 업데이트 요청",
        description = "모듈 펌웨어 업데이트 요청",
        tags = { "디바이스 관리 - 모듈 펌웨어 관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ModuleFirmwareApi.PATH_UPDATE_FIRMWARE_REQUEST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> updateFirmwareRequest(
        @Parameter(name = "UpdateFirmwareRequestRequest", description = "", required = true) @Valid @RequestBody UpdateFirmwareRequestRequest updateFirmwareRequestRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
