/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.openapi.generator.aicc.api;

import com.openapi.generator.aicc.dto.ComResponseSvc;
import com.openapi.generator.aicc.dto.ComResponseSvcList;
import com.openapi.generator.aicc.dto.CreateServiceRequest;
import com.openapi.generator.aicc.dto.DownloadSvcListRequest;
import com.openapi.generator.aicc.dto.RetrieveServiceList1Request;
import com.openapi.generator.aicc.dto.RetrieveServiceRequest;
import com.openapi.generator.aicc.dto.UpdateServiceRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-19T16:30:08.398412+09:00[Asia/Seoul]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "서비스 등록 - 서비스 등록", description = "서비스 등록 - 서비스 등록")
public interface ServiceApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CREATE_SERVICE = "/service/createService";
    /**
     * POST /service/createService : 서비스 등록
     * 서비스 등록
     *
     * @param createServiceRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "createService",
        summary = "서비스 등록",
        description = "서비스 등록",
        tags = { "서비스 등록 - 서비스 등록" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ServiceApi.PATH_CREATE_SERVICE,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> createService(
        @Parameter(name = "CreateServiceRequest", description = "", required = true) @Valid @RequestBody CreateServiceRequest createServiceRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREATE_SERVICE_AUTH = "/service/createServiceAuth";
    /**
     * POST /service/createServiceAuth : 서비스 인증 허용
     * 서비스 인증 허용
     *
     * @param retrieveServiceRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "createServiceAuth",
        summary = "서비스 인증 허용",
        description = "서비스 인증 허용",
        tags = { "서비스 등록 - 서비스 등록" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ServiceApi.PATH_CREATE_SERVICE_AUTH,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> createServiceAuth(
        @Parameter(name = "RetrieveServiceRequest", description = "", required = true) @Valid @RequestBody RetrieveServiceRequest retrieveServiceRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DELETE_SERVICE = "/service/deleteService";
    /**
     * POST /service/deleteService : 서비스 삭제
     * 서비스 삭제
     *
     * @param retrieveServiceRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "deleteService",
        summary = "서비스 삭제",
        description = "서비스 삭제",
        tags = { "서비스 등록 - 서비스 등록" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ServiceApi.PATH_DELETE_SERVICE,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> deleteService(
        @Parameter(name = "RetrieveServiceRequest", description = "", required = true) @Valid @RequestBody RetrieveServiceRequest retrieveServiceRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DELETE_SERVICE_AUTH = "/service/deleteServiceAuth";
    /**
     * POST /service/deleteServiceAuth : 서비스 인증 해제
     * 서비스 인증 해제
     *
     * @param retrieveServiceRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "deleteServiceAuth",
        summary = "서비스 인증 해제",
        description = "서비스 인증 해제",
        tags = { "서비스 등록 - 서비스 등록" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ServiceApi.PATH_DELETE_SERVICE_AUTH,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> deleteServiceAuth(
        @Parameter(name = "RetrieveServiceRequest", description = "", required = true) @Valid @RequestBody RetrieveServiceRequest retrieveServiceRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DOWNLOAD_SVC_LIST = "/service/downloadSvcList";
    /**
     * POST /service/downloadSvcList : 서비스 엑셀 다운로드
     * 서비스 엑셀 다운로드
     *
     * @param downloadSvcListRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "downloadSvcList",
        summary = "서비스 엑셀 다운로드",
        description = "서비스 엑셀 다운로드",
        tags = { "서비스 등록 - 서비스 등록" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ServiceApi.PATH_DOWNLOAD_SVC_LIST,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> downloadSvcList(
        @Parameter(name = "DownloadSvcListRequest", description = "", required = true) @Valid @RequestBody DownloadSvcListRequest downloadSvcListRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_SERVICE = "/service/retrieveService";
    /**
     * POST /service/retrieveService : 서비스 상세 조회
     * 서비스 상세 조회
     *
     * @param retrieveServiceRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveService",
        summary = "서비스 상세 조회",
        description = "서비스 상세 조회",
        tags = { "서비스 등록 - 서비스 등록" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseSvc.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ServiceApi.PATH_RETRIEVE_SERVICE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseSvc> retrieveService(
        @Parameter(name = "RetrieveServiceRequest", description = "", required = true) @Valid @RequestBody RetrieveServiceRequest retrieveServiceRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"cmpCd\" : \"cmpCd\", \"cmpNm\" : \"abacus\", \"svcCd\" : \"svcCd\", \"anPref\" : \"anPref\", \"updUsr\" : \"updUsr\", \"svcDesc\" : \"svcDesc\", \"creDt\" : \"creDt\", \"authYn\" : \"authYn\", \"rolNm\" : \"rolNm\", \"svcNm\" : \"svcNm\", \"expireDuration\" : \"expireDuration\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updDt\" : \"updDt\", \"expireUnit\" : \"expireUnit\" }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_SERVICE_LIST1 = "/service/retrieveServiceList";
    /**
     * POST /service/retrieveServiceList : 서비스 목록 조회
     * 서비스 목록 조회
     *
     * @param retrieveServiceList1Request  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveServiceList1",
        summary = "서비스 목록 조회",
        description = "서비스 목록 조회",
        tags = { "서비스 등록 - 서비스 등록" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseSvcList.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ServiceApi.PATH_RETRIEVE_SERVICE_LIST1,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseSvcList> retrieveServiceList1(
        @Parameter(name = "RetrieveServiceList1Request", description = "", required = true) @Valid @RequestBody RetrieveServiceList1Request retrieveServiceList1Request
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"list\" : [ { \"cmpCd\" : \"cmpCd\", \"cmpNm\" : \"abacus\", \"svcCd\" : \"svcCd\", \"anPref\" : \"anPref\", \"updUsr\" : \"updUsr\", \"svcDesc\" : \"svcDesc\", \"creDt\" : \"creDt\", \"authYn\" : \"authYn\", \"rolNm\" : \"rolNm\", \"svcNm\" : \"svcNm\", \"expireDuration\" : \"expireDuration\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updDt\" : \"updDt\", \"expireUnit\" : \"expireUnit\" }, { \"cmpCd\" : \"cmpCd\", \"cmpNm\" : \"abacus\", \"svcCd\" : \"svcCd\", \"anPref\" : \"anPref\", \"updUsr\" : \"updUsr\", \"svcDesc\" : \"svcDesc\", \"creDt\" : \"creDt\", \"authYn\" : \"authYn\", \"rolNm\" : \"rolNm\", \"svcNm\" : \"svcNm\", \"expireDuration\" : \"expireDuration\", \"useYn\" : \"useYn\", \"creUsr\" : \"creUsr\", \"updDt\" : \"updDt\", \"expireUnit\" : \"expireUnit\" } ], \"totalCount\" : 6 }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_SERVICE = "/service/updateService";
    /**
     * POST /service/updateService : 서비스 수정
     * 서비스 수정
     *
     * @param updateServiceRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "updateService",
        summary = "서비스 수정",
        description = "서비스 수정",
        tags = { "서비스 등록 - 서비스 등록" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ServiceApi.PATH_UPDATE_SERVICE,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> updateService(
        @Parameter(name = "UpdateServiceRequest", description = "", required = true) @Valid @RequestBody UpdateServiceRequest updateServiceRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
