/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.openapi.generator.aicc.api;

import com.openapi.generator.aicc.dto.CheckPasswordIsChangedRequest;
import com.openapi.generator.aicc.dto.ComResponseInteger;
import com.openapi.generator.aicc.dto.ComResponseUser;
import com.openapi.generator.aicc.dto.ComResponseUserIdDuplicate;
import com.openapi.generator.aicc.dto.ComResponseUserList;
import com.openapi.generator.aicc.dto.CreateUserRequest;
import com.openapi.generator.aicc.dto.ResetPasswordRequest;
import com.openapi.generator.aicc.dto.RetrieveUserListRequest;
import com.openapi.generator.aicc.dto.RetrieveUserRequest;
import com.openapi.generator.aicc.dto.UpdateSelfUserRequest;
import com.openapi.generator.aicc.dto.UpdateUserRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-19T16:30:08.398412+09:00[Asia/Seoul]", comments = "Generator version: 7.18.0")
@Validated
@Tag(name = "사용자관리", description = "the 사용자관리 API")
public interface SettingApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CHECK_DUPLICATION_ID = "/setting/user/checkDupId";
    /**
     * POST /setting/user/checkDupId : 아이디 중복 여부 확인
     * 아이디 중복 여부 확인
     *
     * @param resetPasswordRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "checkDuplicationId",
        summary = "아이디 중복 여부 확인",
        description = "아이디 중복 여부 확인",
        tags = { "사용자관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseUserIdDuplicate.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SettingApi.PATH_CHECK_DUPLICATION_ID,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseUserIdDuplicate> checkDuplicationId(
        @Parameter(name = "ResetPasswordRequest", description = "", required = true) @Valid @RequestBody ResetPasswordRequest resetPasswordRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"isDuplicated\" : true }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CHECK_PASSWORD_IS_CHANGED = "/setting/user/checkPasswordIsChanged";
    /**
     * POST /setting/user/checkPasswordIsChanged : 비밀번호 변경 확인
     * 비밀번호 변경 확인 300 - 비밀번호 변경 없음 (기존 비밀번호와 다른 비밀번호를 입력해주세요.) | 상세 이동 가능100 - 예외
     *
     * @param checkPasswordIsChangedRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "checkPasswordIsChanged",
        summary = "비밀번호 변경 확인",
        description = "비밀번호 변경 확인 300 - 비밀번호 변경 없음 (기존 비밀번호와 다른 비밀번호를 입력해주세요.) | 상세 이동 가능100 - 예외",
        tags = { "사용자관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseInteger.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SettingApi.PATH_CHECK_PASSWORD_IS_CHANGED,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseInteger> checkPasswordIsChanged(
        @Parameter(name = "CheckPasswordIsChangedRequest", description = "", required = true) @Valid @RequestBody CheckPasswordIsChangedRequest checkPasswordIsChangedRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : 6, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREATE_USER = "/setting/user/createUser";
    /**
     * POST /setting/user/createUser : 사용자 등록
     * 사용자 등록
     *
     * @param createUserRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "createUser",
        summary = "사용자 등록",
        description = "사용자 등록",
        tags = { "사용자관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SettingApi.PATH_CREATE_USER,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> createUser(
        @Parameter(name = "CreateUserRequest", description = "", required = true) @Valid @RequestBody CreateUserRequest createUserRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DELETE_USER = "/setting/user/deleteUser";
    /**
     * POST /setting/user/deleteUser : 사용자 삭제
     * 사용자 삭제
     *
     * @param resetPasswordRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "deleteUser",
        summary = "사용자 삭제",
        description = "사용자 삭제",
        tags = { "사용자관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SettingApi.PATH_DELETE_USER,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> deleteUser(
        @Parameter(name = "ResetPasswordRequest", description = "", required = true) @Valid @RequestBody ResetPasswordRequest resetPasswordRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RESET_PASSWORD = "/setting/user/resetPassword";
    /**
     * POST /setting/user/resetPassword : 임시 비밀번호 발급
     * 임시 비밀번호 발급
     *
     * @param resetPasswordRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "resetPassword",
        summary = "임시 비밀번호 발급",
        description = "임시 비밀번호 발급",
        tags = { "사용자관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SettingApi.PATH_RESET_PASSWORD,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> resetPassword(
        @Parameter(name = "ResetPasswordRequest", description = "", required = true) @Valid @RequestBody ResetPasswordRequest resetPasswordRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_SELF_USER = "/setting/retrieveSelfUser";
    /**
     * POST /setting/retrieveSelfUser : 사용자 개인 정보 조회
     * 사용자 개인 정보 조회
     *
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveSelfUser",
        summary = "사용자 개인 정보 조회",
        description = "사용자 개인 정보 조회",
        tags = { "사용자관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseUser.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SettingApi.PATH_RETRIEVE_SELF_USER,
        produces = { "application/json" }
    )
    default ResponseEntity<ComResponseUser> retrieveSelfUser(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"cmpNm\" : \"LG UPLUS\", \"description\" : \"설명\", \"changeLog\" : \"changeLog\", \"usrPhone\" : \"01099999999\", \"loginCnt\" : 6, \"rolNm\" : \"ROLE_PROJECT\", \"usrNm\" : \"관리자 계정\", \"useYn\" : \"Y\", \"email\" : \"example@example.com\", \"prfLangCd\" : \"en\", \"smsNum\" : \"smsNum\", \"cmpCd\" : \"1\", \"passedYn\" : \"passedYn\", \"usrId\" : \"admin\", \"updUsr\" : \"updUsr\", \"isAdmin\" : true, \"creDt\" : \"creDt\", \"privateKey\" : \"bD98e5GiiCienMsnzl8POWnvChH2Zd2mIscJpMBvyc0\", \"rols\" : [ \"rols\", \"rols\" ], \"opPasswd\" : \"opPasswd\", \"serviceList\" : \"T003,T002,T006\", \"usrPwd\" : \"abc123!@\", \"passedDays\" : 1, \"cmpType\" : \"cmpType\", \"creUsr\" : \"creUsr\", \"updDt\" : \"updDt\", \"pwdSetTime\" : \"pwdSetTime\", \"oldUsrPwd\" : \"abc123!@\" }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_USER = "/setting/user/retrieveUser";
    /**
     * POST /setting/user/retrieveUser : 사용자 상세 조회
     * 사용자 상세 조회
     *
     * @param retrieveUserRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveUser",
        summary = "사용자 상세 조회",
        description = "사용자 상세 조회",
        tags = { "사용자관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseUser.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SettingApi.PATH_RETRIEVE_USER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseUser> retrieveUser(
        @Parameter(name = "RetrieveUserRequest", description = "", required = true) @Valid @RequestBody RetrieveUserRequest retrieveUserRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"cmpNm\" : \"LG UPLUS\", \"description\" : \"설명\", \"changeLog\" : \"changeLog\", \"usrPhone\" : \"01099999999\", \"loginCnt\" : 6, \"rolNm\" : \"ROLE_PROJECT\", \"usrNm\" : \"관리자 계정\", \"useYn\" : \"Y\", \"email\" : \"example@example.com\", \"prfLangCd\" : \"en\", \"smsNum\" : \"smsNum\", \"cmpCd\" : \"1\", \"passedYn\" : \"passedYn\", \"usrId\" : \"admin\", \"updUsr\" : \"updUsr\", \"isAdmin\" : true, \"creDt\" : \"creDt\", \"privateKey\" : \"bD98e5GiiCienMsnzl8POWnvChH2Zd2mIscJpMBvyc0\", \"rols\" : [ \"rols\", \"rols\" ], \"opPasswd\" : \"opPasswd\", \"serviceList\" : \"T003,T002,T006\", \"usrPwd\" : \"abc123!@\", \"passedDays\" : 1, \"cmpType\" : \"cmpType\", \"creUsr\" : \"creUsr\", \"updDt\" : \"updDt\", \"pwdSetTime\" : \"pwdSetTime\", \"oldUsrPwd\" : \"abc123!@\" }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_RETRIEVE_USER_LIST = "/setting/user/retrieveUserList";
    /**
     * POST /setting/user/retrieveUserList : 사용자 목록 조회
     * 사용자 목록 조회
     *
     * @param retrieveUserListRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "retrieveUserList",
        summary = "사용자 목록 조회",
        description = "사용자 목록 조회",
        tags = { "사용자관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ComResponseUserList.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SettingApi.PATH_RETRIEVE_USER_LIST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<ComResponseUserList> retrieveUserList(
        @Parameter(name = "RetrieveUserListRequest", description = "", required = true) @Valid @RequestBody RetrieveUserListRequest retrieveUserListRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"errorMessage\" : \"errorMessage\", \"detailMessage\" : \"detailMessage\", \"message\" : \"message\", \"body\" : { \"list\" : [ { \"cmpNm\" : \"LG UPLUS\", \"description\" : \"설명\", \"changeLog\" : \"changeLog\", \"usrPhone\" : \"01099999999\", \"loginCnt\" : 6, \"rolNm\" : \"ROLE_PROJECT\", \"usrNm\" : \"관리자 계정\", \"useYn\" : \"Y\", \"email\" : \"example@example.com\", \"prfLangCd\" : \"en\", \"smsNum\" : \"smsNum\", \"cmpCd\" : \"1\", \"passedYn\" : \"passedYn\", \"usrId\" : \"admin\", \"updUsr\" : \"updUsr\", \"isAdmin\" : true, \"creDt\" : \"creDt\", \"privateKey\" : \"bD98e5GiiCienMsnzl8POWnvChH2Zd2mIscJpMBvyc0\", \"rols\" : [ \"rols\", \"rols\" ], \"opPasswd\" : \"opPasswd\", \"serviceList\" : \"T003,T002,T006\", \"usrPwd\" : \"abc123!@\", \"passedDays\" : 1, \"cmpType\" : \"cmpType\", \"creUsr\" : \"creUsr\", \"updDt\" : \"updDt\", \"pwdSetTime\" : \"pwdSetTime\", \"oldUsrPwd\" : \"abc123!@\" }, { \"cmpNm\" : \"LG UPLUS\", \"description\" : \"설명\", \"changeLog\" : \"changeLog\", \"usrPhone\" : \"01099999999\", \"loginCnt\" : 6, \"rolNm\" : \"ROLE_PROJECT\", \"usrNm\" : \"관리자 계정\", \"useYn\" : \"Y\", \"email\" : \"example@example.com\", \"prfLangCd\" : \"en\", \"smsNum\" : \"smsNum\", \"cmpCd\" : \"1\", \"passedYn\" : \"passedYn\", \"usrId\" : \"admin\", \"updUsr\" : \"updUsr\", \"isAdmin\" : true, \"creDt\" : \"creDt\", \"privateKey\" : \"bD98e5GiiCienMsnzl8POWnvChH2Zd2mIscJpMBvyc0\", \"rols\" : [ \"rols\", \"rols\" ], \"opPasswd\" : \"opPasswd\", \"serviceList\" : \"T003,T002,T006\", \"usrPwd\" : \"abc123!@\", \"passedDays\" : 1, \"cmpType\" : \"cmpType\", \"creUsr\" : \"creUsr\", \"updDt\" : \"updDt\", \"pwdSetTime\" : \"pwdSetTime\", \"oldUsrPwd\" : \"abc123!@\" } ], \"totalCount\" : 6 }, \"httpStatusCode\" : 0, \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_SELF_USER = "/setting/updateSelfUser";
    /**
     * POST /setting/updateSelfUser : 사용자 개인 정보 수정
     * 사용자 개인 정보 수정
     *
     * @param updateSelfUserRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "updateSelfUser",
        summary = "사용자 개인 정보 수정",
        description = "사용자 개인 정보 수정",
        tags = { "사용자관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SettingApi.PATH_UPDATE_SELF_USER,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> updateSelfUser(
        @Parameter(name = "UpdateSelfUserRequest", description = "", required = true) @Valid @RequestBody UpdateSelfUserRequest updateSelfUserRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_USER = "/setting/user/updateUser";
    /**
     * POST /setting/user/updateUser : 사용자 수정
     * 사용자 수정
     *
     * @param updateUserRequest  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "updateUser",
        summary = "사용자 수정",
        description = "사용자 수정",
        tags = { "사용자관리" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = SettingApi.PATH_UPDATE_USER,
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> updateUser(
        @Parameter(name = "UpdateUserRequest", description = "", required = true) @Valid @RequestBody UpdateUserRequest updateUserRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
